=== tella22/DUAL/Marcas/2evaluacion/DTD/Tella-Jose_Antonio-DTD/practica 8/practica8.dtd
<!ELEMENT ediciones_aranda (informe_regional_de_ventas)>
<!ELEMENT informe_regional_de_ventas (region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?, region, trimestre*, libros_vendidos?)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>
<!ATTLIST informe_regional_de_ventas descripcion CDATA #REQUIRED>
<!ATTLIST informe_regional_de_ventas fecha CDATA #REQUIRED>

=== tella22/DUAL/Marcas/2evaluacion/DTD/Tella-Jose_Antonio-DTD/practica 8/practica8.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE ediciones_aranda SYSTEM "practica8.dtd">

<ediciones_aranda>
	<informe_regional_de_ventas descripcion="informe de ventas para las regiones Norte, Centro y Sur" fecha="30/12/2016">
		<region>norte</region>
		<trimestre>1</trimestre>
		<libros_vendidos>24000</libros_vendidos>
		<region>norte</region>
		<trimestre>2</trimestre>
		<libros_vendidos>38600</libros_vendidos>
		<region>norte</region>
		<trimestre>3</trimestre>
		<libros_vendidos></libros_vendidos>
		<region>norte</region>
		<trimestre>4</trimestre>
		<libros_vendidos></libros_vendidos>
		<region>centro</region>
		<trimestre>1</trimestre>
		<libros_vendidos></libros_vendidos>
		<region>centro</region>
		<trimestre>2</trimestre>
		<libros_vendidos>16080</libros_vendidos>
		<region>centro</region>
		<trimestre>3</trimestre>
		<libros_vendidos>25000</libros_vendidos>
		<region>centro</region>
		<trimestre>4</trimestre>
		<libros_vendidos>29000</libros_vendidos>
		<region>sur</region>
		<trimestre>1</trimestre>
		<libros_vendidos>27000</libros_vendidos>
		<region>sur</region>
		<trimestre>2</trimestre>
		<libros_vendidos>31400</libros_vendidos>
		<region>sur</region>
		<trimestre>3</trimestre>
		<libros_vendidos>40100</libros_vendidos>
		<region>sur</region>
		<trimestre>4</trimestre>
		<libros_vendidos>30000</libros_vendidos>
	</informe_regional_de_ventas>
</ediciones_aranda>
