<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE persona [

<!ELEMENT persona (nombre,nacimiento?,direccion+,varon)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento
  anyo CDATA #REQUIRED
  dia CDATA #REQUIRED
  mes NMTOKEN #REQUIRED>

<!ELEMENT direccion (calle,poblacion,provincia,cpostal)>

<!ELEMENT varon EMPTY>

<!ELEMENT calle (#PCDATA)>

<!ELEMENT poblacion (#PCDATA)>

<!ELEMENT provincia (#PCDATA)>

<!ELEMENT cpostal (#PCDATA)>
]>

<persona>

  <nombre>Juan Pardo</nombre>
  <nacimiento dia="10" mes="Abril" anyo="1982"></nacimiento>
  <direccion>
    <calle>Caoba, 1</calle>
    <poblacion>Madrid</poblacion>
    <provincia>Madrid</provincia>
    <cpostal>28005</cpostal>
  </direccion>
  <varon></varon>
  
</persona>