<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE lista_de_notas [
	<!ELEMENT lista_de_notas (nota)>
	<!ELEMENT nota (para, de, titulo, contenido)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT de (#PCDATA)>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT contenido (#PCDATA)>
	<!ATTLIST nota dia CDATA "23/01/2010">
	<!ATTLIST nota hora CDATA "13:15">
]>
<lista_de_notas>
  <nota>
    <para>Pedro</para>
    <de>Laura</de>
    <titulo>Recordatorio</titulo>
    <contenido>A las 7:00 pm en la puerta del teatro </contenido>
  </nota>
  <nota dia="23/01/2010" hora="13:15">
    <para>Miguel</para>
    <de>Juan</de>
    <titulo>Informes</titulo>
    <contenido>Te he dejado los informes en el casillero</contenido>
  </nota>
</lista_de_notas>
