=== tella22/DUAL/Marcas/2evaluacion/DTD/Avanzados/practica 3/practica3.dtd
<!ELEMENT modelos (modelo+)>
<!ELEMENT modelo (modelos_relacionados?,
                  (descripcion,motor)?)>
<!ATTLIST modelo id ID #REQUIRED>

<!ELEMENT modelos_relacionados (#PCDATA)>
<!ATTLIST modelos_relacionados idrefs IDREFS #REQUIRED>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion>

<!ELEMENT motor (#PCDATA)>
<!ATTLIST motor idref IDREF #REQUIRED>

=== tella22/DUAL/Marcas/2evaluacion/DTD/Avanzados/practica 3/practica3.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE modelos SYSTEM "practica3.dtd">

<modelos>
  <modelo id="I556"></modelo>
  
  <modelo id="I555">
    <modelos_relacionados idrefs="I444 I556">
    </modelos_relacionados>
    <descripcion>
      Este modelo tiene un motor 1.998cc 16v. de cuatro cilindros, que desarrolla una potencia de 128 CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 11 a los 100 km. El precio base es de 2.225.000.
    </descripcion>
    <motor idref="I556"></motor>
  </modelo>

  <modelo id="I557"></modelo>

  <modelo id="I154"></modelo>

  <modelo id="I444">
    
    <modelos_relacionados idrefs="I555 I154">
    </modelos_relacionados>
    <descripcion>
      Este modelo tiene un motor 2.000cc 16v. de cuatro cilindros con 128 CV. Dispone de cambio manual ... el consumo medio de este monovolumen es 11 a los 100 km. El precio base es de 2.500.000.
    </descripcion>
    <motor idref="I556"></motor>
  </modelo>
  
</modelos>
