=== tella22/DUAL/Marcas/2evaluacion/trabajo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://w3schools.com"
           xmlns="https://w3schools.com"
           elementFormDefault="qualified">
  
  <xs:element name="resultado" type="resultadoType"/>

  <xs:complexType name="resultadoType">
    <xs:sequence>
      <xs:element name="totalCount" type="xs:int"/>
      <xs:element name="start" type="xs:int"/>
      <xs:element name="rows" type="xs:int"/>
      <xs:element name="result" type="resultado"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="resultado">
      <xs:sequence>
        <xs:element name="servicio-duelo" type="servicio" minOccurs="1" maxOccurs="200"/>
      </xs:sequence>
  </xs:complexType>

  <xs:complexType name="servicio">
    <xs:sequence>
      <xs:element name="id" id="id" type="xs:int"/>
      <xs:element name="salaDate" type="xs:dateTime"/>
      <xs:element name="numeroVelatorio" type="xs:NMTOKEN"/>
      <xs:element name="numeroSala" type="xs:string"/>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="primerApellido" type="xs:string"/>
      <xs:element name="segundoApellido" type="xs:string"/>
      <xs:element name="horaSala" type="xs:time"/>
      <xs:element name="lastUpdated" minOccurs="0" type="xs:dateTime"/>
      <xs:element name="pubDate" type="xs:dateTime"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== tella22/DUAL/Marcas/2evaluacion/trabajo.xml
<?xml version="1.0"?>
<resultado xmlns="https://w3schools.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="trabajo.xsd">
  <totalCount>33</totalCount>
  <start>0</start>
  <rows>50</rows>
  <result>
    <servicio-duelo>
      <id>76265</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>11</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Eladia</nombre>
      <primerApellido>Aladren</primerApellido>
      <segundoApellido>Camino</segundoApellido>
      <horaSala>11:00:00</horaSala>
      <lastUpdated>2018-03-01T13:02:32Z</lastUpdated>
      <pubDate>2018-03-01T13:02:23Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76267</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>6</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Maria Pilar</nombre>
      <primerApellido>Barcelona</primerApellido>
      <segundoApellido>Martinez</segundoApellido>
      <horaSala>11:30:00</horaSala>
      <pubDate>2018-03-01T13:11:25Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76266</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>2</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Josefa</nombre>
      <primerApellido>Garcia</primerApellido>
      <segundoApellido>Sorrosal</segundoApellido>
      <horaSala>13:00:00</horaSala>
      <lastUpdated>2018-03-01T13:10:36Z</lastUpdated>
      <pubDate>2018-03-01T13:10:07Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76287</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>12</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Felix</nombre>
      <primerApellido>Gargallo</primerApellido>
      <segundoApellido>Garcia</segundoApellido>
      <horaSala>09:00:00</horaSala>
      <pubDate>2018-03-01T13:08:15Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76285</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>4</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Joaquina</nombre>
      <primerApellido>Puerta</primerApellido>
      <segundoApellido>Diaz</segundoApellido>
      <horaSala>09:30:00</horaSala>
      <lastUpdated>2018-03-01T13:06:58Z</lastUpdated>
      <pubDate>2018-03-01T13:06:52Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76284</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>3</numeroVelatorio>
      <numeroSala>San Juan De Mozarrifar</numeroSala>
      <nombre>Alejandro Manuel</nombre>
      <primerApellido>Sanchez</primerApellido>
      <segundoApellido>Gracia</segundoApellido>
      <horaSala>10:00:00</horaSala>
      <pubDate>2018-03-01T13:05:08Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76264</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>17</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Teresa</nombre>
      <primerApellido>Sanchez De Pablo</primerApellido>
      <segundoApellido>Marin De Bernardo</segundoApellido>
      <horaSala>10:00:00</horaSala>
      <lastUpdated>2018-03-01T13:01:42Z</lastUpdated>
      <pubDate>2018-03-01T13:01:35Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76286</id>
      <salaDate>2018-03-01T23:00:00Z</salaDate>
      <numeroVelatorio>1</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Vicenta</nombre>
      <primerApellido>Ubau</primerApellido>
      <segundoApellido>Miguel</segundoApellido>
      <horaSala>10:30:00</horaSala>
      <pubDate>2018-03-01T13:07:41Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76244</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>-</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Genoveva</nombre>
      <primerApellido>Angles</primerApellido>
      <segundoApellido>Bonfil</segundoApellido>
      <horaSala>16:15:00</horaSala>
      <pubDate>2018-02-28T13:25:24Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76227</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>7</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Josefa</nombre>
      <primerApellido>Burguete</primerApellido>
      <segundoApellido>Llopis</segundoApellido>
      <horaSala>17:00:00</horaSala>
      <lastUpdated>2018-02-28T13:22:11Z</lastUpdated>
      <pubDate>2018-02-28T13:22:05Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76248</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>16</numeroVelatorio>
      <numeroSala>Salida de Velatorio</numeroSala>
      <nombre>Carmen</nombre>
      <primerApellido>Garcia</primerApellido>
      <segundoApellido>Prat</segundoApellido>
      <horaSala>10:15:00</horaSala>
      <lastUpdated>2018-02-28T13:29:27Z</lastUpdated>
      <pubDate>2018-02-28T13:29:05Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76247</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>15</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Trinidad</nombre>
      <primerApellido>Lite</primerApellido>
      <segundoApellido>Morales</segundoApellido>
      <horaSala>11:00:00</horaSala>
      <pubDate>2018-02-28T13:28:10Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76245</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>5</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Carmen</nombre>
      <primerApellido>Lopez</primerApellido>
      <segundoApellido>Gonzalez</segundoApellido>
      <horaSala>10:30:00</horaSala>
      <lastUpdated>2018-02-28T13:26:50Z</lastUpdated>
      <pubDate>2018-02-28T13:26:41Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76225</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>1</numeroVelatorio>
      <numeroSala>2</numeroSala>
      <nombre>Casta Maria</nombre>
      <primerApellido>Molina</primerApellido>
      <segundoApellido>Cañete</segundoApellido>
      <horaSala>13:15:00</horaSala>
      <pubDate>2018-02-28T13:17:40Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76246</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>6</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Fernando</nombre>
      <primerApellido>Morlanes</primerApellido>
      <segundoApellido>Perez</segundoApellido>
      <horaSala>10:00:00</horaSala>
      <lastUpdated>2018-02-28T13:27:37Z</lastUpdated>
      <pubDate>2018-02-28T13:27:31Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76226</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>12</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Juan Carlos</nombre>
      <primerApellido>Muntadas</primerApellido>
      <segundoApellido>Torres</segundoApellido>
      <horaSala>16:00:00</horaSala>
      <pubDate>2018-02-28T13:21:12Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76251</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>-</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Felisa</nombre>
      <primerApellido>Pellejero</primerApellido>
      <segundoApellido>Cebollada</segundoApellido>
      <horaSala>12:30:00</horaSala>
      <pubDate>2018-02-28T13:31:47Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76252</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>-</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Jose Luis</nombre>
      <primerApellido>Santamaria</primerApellido>
      <segundoApellido>Labarta</segundoApellido>
      <horaSala>13:00:00</horaSala>
      <pubDate>2018-02-28T13:32:17Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76250</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>14</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Carlota</nombre>
      <primerApellido>Tubio</primerApellido>
      <segundoApellido>Manzano</segundoApellido>
      <horaSala>11:30:00</horaSala>
      <pubDate>2018-02-28T13:31:12Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76249</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>13</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Carmen</nombre>
      <primerApellido>Valtueña</primerApellido>
      <segundoApellido>Notivol</segundoApellido>
      <horaSala>12:00:00</horaSala>
      <lastUpdated>2018-02-28T13:30:35Z</lastUpdated>
      <pubDate>2018-02-28T13:30:25Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76228</id>
      <salaDate>2018-02-28T23:00:00Z</salaDate>
      <numeroVelatorio>2</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Milagros</nombre>
      <primerApellido>Viartola</primerApellido>
      <segundoApellido>Tosaus</segundoApellido>
      <horaSala>09:00:00</horaSala>
      <pubDate>2018-02-28T13:23:29Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76224</id>
      <salaDate>2018-02-27T23:00:00Z</salaDate>
      <numeroVelatorio>4</numeroVelatorio>
      <numeroSala>3</numeroSala>
      <nombre>Joaquin</nombre>
      <primerApellido>Campos</primerApellido>
      <segundoApellido>Loriente</segundoApellido>
      <horaSala>13:30:00</horaSala>
      <pubDate>2018-02-28T13:16:48Z</pubDate>
    </servicio-duelo>
    <servicio-duelo>
      <id>76209</id>
      <salaDate>2018-02-27T23:00:00Z</salaDate>
      <numeroVelatorio>14</numeroVelatorio>
      <numeroSala>1</numeroSala>
      <nombre>Hipolito</nombre>
      <primerApellido>Dominguez</primerApellido>
      <segundoApellido>Dominguez</segundoApellido>
      <horaSala>11:00:00</horaSala>
      <lastUpdated>2018-02-27T15:25:50Z</lastUpdated>
      <pubDate>2018-02-27T15:25:44Z</pubDate>
